#!/bin/sh

set -e

case "$1" in
    configure|upgrade|update|reconfigure|triggered)
        

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
